In [1]:
mylist = [1,2,3,4]

In [2]:
mylist.pop()

4

In [3]:
mylist

[1, 2, 3]

In [4]:
class stack():
    def __init__(self):
        self.items = []
        
    def isEmpty(self):
        return self.items==[]

    def push(self, data):
        self.items.append(data)

    def pop(self):
        if len(self.items) > 0:
            return self.items.pop()
        else:
            raise Exception("Cannot pop from an empty stack")

    def peek(self):
        if self.items == []:
            return []
        else:
            return self.items[-1]

    def size(self):
        return len(self.items)

    def print(self):
        return self.items

    def copy(self):
        return self

In [5]:
mystack = stack()

In [6]:
mystack.isEmpty()

True

In [7]:
mystack.push(3)

In [8]:
mystack.push(8)

In [9]:
mystack.isEmpty()

False

In [10]:
mystack.push(9)

In [11]:
mystack.push(23)

In [12]:
mystack.push(4)

In [13]:
mystack.print()

[3, 8, 9, 23, 4]

In [14]:
mystack.pop()

4

In [15]:
mystack.print()

[3, 8, 9, 23]

In [16]:
mystack.peek()

23

# Timing the Data structures

## Appending

Both data structures will append a set of 1000 numbers 100 times. They will then be timed.

In [17]:
import numpy as np

In [18]:
# numpy array appending from the front

def array_adder(n):
    array_slow = np.array([])
    for j in range(n):
        array_slow = np.insert(array_slow, 0, j, axis=None)
    return array_slow

In [19]:
%timeit array_adder(1_000_00)

2.11 s ± 343 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
# List adding from front

def list_adder_slow(n):
    front_list = []
    for i in range(n):
        front_list.insert(0, i)
    return front_list

In [21]:
%timeit list_adder_slow(1_000_00)

2.53 s ± 48.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [22]:
# stack adding

def stack_adder(n):
    stacker = stack()
    for i in range(n):
        stacker.push(i)
    return stacker.items

In [23]:
%timeit stack_adder(1_000_00)

3.78 ms ± 73.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Thus, the stack preserves the LIFO efficiently, since it forces the user to only take out the top of the stack. The array and list have to be appended from the from the make the order seem intuitive to the user, but then these take very long.

In [24]:
print(array_adder(10))
print(list_adder_slow(10))
print(stack_adder(10))

[9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## Deletion

Since it is a LIFO system, deletion will be from the back of the arrays. For a stack it can only be through `pop`

In [25]:
# Creating the data structures
del_list = []
for i in range(1_000_00):
    del_list.insert(0, i)
del_array = np.array(del_list)
del_array

array([99999, 99998, 99997, ...,     2,     1,     0], shape=(100000,))

In [26]:
del_stack = stack()
for i in reversed(del_list):
    del_stack.push(i)
del_stack.peek()

99999

In [27]:
def list_deleter(A):
    # Copying the list so that we do not edit the original list
    temp = A.copy()
    for i in range(len(temp)):
        temp.pop(0)

In [28]:
%timeit list_deleter(del_list)

792 ms ± 13.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:
def array_deleter(A):
    for i in range(len(A)):
        A = np.delete(A, 0)
    return A

In [30]:
%timeit array_deleter(del_array)

1.27 s ± 62.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
def stack_deleter(A):
    # initialising and then copying the stack items so we do not edit the orginal stack
    temp = stack()
    temp.items = A.items.copy()
    for i in range(temp.size()):
        temp.pop()

In [32]:
%timeit stack_deleter(del_stack)

5.22 ms ± 140 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Thus, a stack is faster when a LIFO regime is enforced as compared to a numpy array and a python list

## Accessing

First we need to create the arrays and the stack containing the elements. In essence, the front most elements will be 0,1,2,...

In [33]:
access_list = [i for i in range(1_000_000)]
access_array = np.array(access_list)
access_array

array([     0,      1,      2, ..., 999997, 999998, 999999],
      shape=(1000000,))

In [34]:
access_stack = stack()
for i in reversed(access_list):
    access_stack.push(i)
access_stack.peek()    

0

## Accessing an element in an array

Say we want to access a random element

In [35]:
def array_accessor_number(A):
    number = np.random.randint(0,len(A))
    for i in A:
        if i==number:
            return number
        else:
            return -1

In [36]:
%timeit array_accessor_number(access_array)

954 ns ± 10.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Or if we want to access a random index

In [37]:
def array_accessor_index(A):
    index = np.random.randint(0,len(A))
    return A[index]

In [38]:
%timeit array_accessor_index(access_array)

935 ns ± 18.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Access an element in a stack

For a stack, elements on top need to be removed in order to access it

In [39]:
def stack_accessor(A):
    temp = stack()
    temp.items = A.items.copy()

    number = np.random.randint(0, temp.size())
    for i in range(temp.size()):
        if temp.peek()==number:
            return number
        else:
            temp.pop()
    return -1

In [40]:
%timeit stack_accessor(access_stack)

54.8 ms ± 9.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Thus, the stack may not be the most efficient for accessing elements that are not the top element

# Using a singly linked list to make a stack

First, we need to set up the basic infrastructure for a singly linked list

In [41]:
class SNode:
    def __init__(self, elem=None, next=None):
        self.elem = elem
        self.next = next

class SList:
    def __init__(self, head=None):
        self.head = head

Then, we set up the necessary operations needed for a stack

In [42]:
class linked_stack:
    def __init__(self):
        self.list = SList()
        self.count = 0

    def isEmpty(self):
        return self.count==0

    def push(self, item):
        # Initialise the new node with the specified item and the next pointer to the head of the list
        newnode = SNode(item, self.list.head)
        # Designate the new node as the new header
        self.list.head = newnode
        # Add one to the count
        self.count += 1

    def pop(self):
        # If list empty, return an error
        if self.count==0:
            raise Exception("Cannot pop from an empty stack")
        # Temporarily store the element of the popped node
        temp = self.list.head.elem
        # Shift the header pointer to the next element
        self.list.head = self.list.head.next
        # Decrease the count
        self.count -= 1
        # Return the popped element
        return temp

    def peek(self):
        if self.isEmpty():
            return "Empty"
        else:
            return self.list.head.elem

    def size(self):
        return self.count

In [43]:
linky_stack = linked_stack()
linky_stack.push(3)
linky_stack.push(7)
linky_stack.push(1)
linky_stack.peek()

1

In [44]:
linky_stack.size()

3

In [45]:
linky_stack.pop()

1

In [46]:
linky_stack.peek()

7

# Comparing this Data structures to the list-based stack

In [47]:
def list_pusher(n):
    list_stack = stack()
    for i in range(n):
        list_stack.push(i)
    return list_stack

In [48]:
%timeit list_pusher(100_000)

3.67 ms ± 110 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [49]:
def linky_pusher(n):
    linky_stack = linked_stack()
    for i in range(n):
        linky_stack.push(i)
    return linky_stack

In [50]:
%timeit linky_pusher(100_000)

14.2 ms ± 292 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Thus, it seems like python's built-in list is still faster

In [51]:
del_stack = list_pusher(100_000)
del_linky_stack = linky_pusher(100_000)

In [52]:
def list_popper(A):
    temp = stack()
    temp.items = A.items.copy()
    for i in range(A.size()):
        temp.pop()

In [53]:
%timeit list_popper(del_stack)

5.1 ms ± 66.4 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [54]:
def linky_popper(A):
    temp = linked_stack()
    temp.list.head = A.list.head
    temp.count = A.count
    for i in range(A.size()):
        temp.pop()
    return temp

In [55]:
%timeit linky_popper(del_linky_stack)

6.87 ms ± 50.3 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Interestingly, the list is still faster than the linked list, but not by much this time